version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: hi-nest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin   
      POSTGRES_PASSWORD: q1w2e3r4!  
      POSTGRES_DB: hi_nest_db     
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: